// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjEaUYiRmjdcgOGlz_eBI0kcgXhKy-Llg',
    appId: '1:104864831984:web:530d0377022b9904326535',
    messagingSenderId: '104864831984',
    projectId: 'techhub-2b9aa',
    authDomain: 'techhub-2b9aa.firebaseapp.com',
    storageBucket: 'techhub-2b9aa.firebasestorage.app',
    measurementId: 'G-XDTXG74FGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3vhV6-9ITEu_EpNpd1l49AwxoFoc2fPo',
    appId: '1:104864831984:android:cc901c65b1b68a63326535',
    messagingSenderId: '104864831984',
    projectId: 'techhub-2b9aa',
    storageBucket: 'techhub-2b9aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBijLbxzMiuZxk4iGqxIxUVaQzBcJlrB30',
    appId: '1:104864831984:ios:4108de20ec3c6f72326535',
    messagingSenderId: '104864831984',
    projectId: 'techhub-2b9aa',
    storageBucket: 'techhub-2b9aa.firebasestorage.app',
    iosBundleId: 'com.example.assignmant3',
  );
}
